# Generated by Django 4.0.4 on 2022-05-05 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['complete']},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='content',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 5, 11, 36, 35, 364814, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 5, 5, 11, 37, 0, 234502, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
